// Differential conformance test: rrule-ts vs python-dateutil.
//
// The corpus (corpus/corpus.json) was generated by running the fast-check
// generator + hardcoded RFC §3.8.5.3 + DST seed cases through the Python
// dateutil oracle. It is committed so CI is hermetic: Python is not needed
// to run these tests, only to regenerate the corpus.
//
// EXPANSION PHASE INSTRUCTION:
//   Once expand() is implemented, flip every `it.todo` to a real `it` and
//   remove the `describe.skip` wrapper. The diff assertions are already
//   written — just uncomment them.
//
// ACTIVE TEST: corpus sanity check (always runs, never skipped).
// DIFF TESTS: it.todo — not failing, kept as pending until expand() is real.

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'

// expand() is imported but not called in the active tests.
// It will be wired in the expansion phase.
import { expand } from 'rrule-ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const corpusPath = resolve(__dirname, '..', 'corpus', 'corpus.json')

// ---------------------------------------------------------------------------
// Corpus type
// ---------------------------------------------------------------------------

interface CorpusCase {
  id: string
  label: string
  rrule: string
  dtstart: string
  tzid: string | null
  count: number
  expectedOccurrences: string[]
}

interface Corpus {
  version: string
  oracleVersion: string
  generatedAt: string
  totalCases: number
  cases: CorpusCase[]
}

// ---------------------------------------------------------------------------
// Load corpus once
// ---------------------------------------------------------------------------

const corpus: Corpus = JSON.parse(readFileSync(corpusPath, 'utf-8'))

// ---------------------------------------------------------------------------
// ACTIVE: corpus sanity checks — always run, prove the harness is not vacuous
// ---------------------------------------------------------------------------

describe('conformance corpus sanity', () => {
  it('corpus file loads and is non-empty', () => {
    expect(corpus).toBeDefined()
    expect(corpus.cases).toBeInstanceOf(Array)
    expect(corpus.cases.length).toBeGreaterThan(0)
  })

  it('corpus has required metadata fields', () => {
    expect(corpus.version).toBe('1')
    expect(corpus.oracleVersion).toContain('python-dateutil')
    expect(corpus.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/)
    expect(corpus.totalCases).toBe(corpus.cases.length)
  })

  it('every case has required fields (id, label, rrule, dtstart, count, expectedOccurrences)', () => {
    for (const c of corpus.cases) {
      expect(c.id, `case ${c.id}: missing id`).toBeTruthy()
      expect(c.label, `case ${c.id}: missing label`).toBeTruthy()
      expect(c.rrule, `case ${c.id}: missing rrule`).toBeTruthy()
      expect(c.dtstart, `case ${c.id}: missing dtstart`).toBeTruthy()
      expect(c.count, `case ${c.id}: count must be >= 1`).toBeGreaterThanOrEqual(1)
      expect(c.expectedOccurrences, `case ${c.id}: missing expectedOccurrences`).toBeInstanceOf(
        Array
      )
      expect(
        c.expectedOccurrences.length,
        `case ${c.id}: expectedOccurrences is empty`
      ).toBeGreaterThan(0)
    }
  })

  it('every expectedOccurrence is an ISO-8601-like string', () => {
    for (const c of corpus.cases) {
      for (const occ of c.expectedOccurrences) {
        expect(occ, `case ${c.id}: occurrence "${occ}" must be ISO-8601`).toMatch(
          /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(Z|[+-]\d{2}:\d{2})?)?$/
        )
      }
    }
  })

  it('corpus covers all 7 FREQ values', () => {
    const freqSet = new Set(corpus.cases.map((c) => c.rrule.match(/FREQ=(\w+)/)?.[1]))
    for (const freq of ['SECONDLY', 'MINUTELY', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY']) {
      expect(freqSet, `corpus must include at least one ${freq} case`).toContain(freq)
    }
  })

  it('corpus includes DST cases for expected zones', () => {
    const tzids = new Set(corpus.cases.map((c) => c.tzid).filter(Boolean))
    expect(tzids).toContain('America/Los_Angeles')
    expect(tzids).toContain('Europe/Berlin')
    expect(tzids).toContain('Australia/Lord_Howe')
    expect(tzids).toContain('Pacific/Apia')
  })

  it('corpus includes RFC §3.8.5.3 seed cases', () => {
    const ids = new Set(corpus.cases.map((c) => c.id))
    // Spot-check a few of the hardcoded RFC cases by id.
    expect(ids).toContain('rfc-daily-count-10')
    expect(ids).toContain('rfc-weekly-count-10')
    expect(ids).toContain('rfc-monthly-bysetpos-neg1-th')
    expect(ids).toContain('rfc-yearly-byweekno-20-mo')
  })
})

// ---------------------------------------------------------------------------
// PENDING: differential diff assertions.
//
// ENABLE IN EXPANSION PHASE — flip it.todo -> it (remove .todo) once
// expand() is implemented. The test logic is already written below in the
// describe.skip block; just change describe.skip -> describe.
//
// Why describe.skip rather than it.todo: the diff loop needs to reference
// the corpus at module load time; it.todo only accepts a name string.
// Using describe.skip keeps the full test code visible and type-checked while
// ensuring the suite stays green without a working expand().
// ---------------------------------------------------------------------------

describe.skip('conformance diff: rrule-ts expand() vs dateutil oracle — ENABLE IN EXPANSION PHASE', () => {
  // When enabled, this will run one assertion per corpus case.
  for (const c of corpus.cases) {
    it(`${c.id}: ${c.label}`, () => {
      // Parse the combined input string that gen-corpus produces.
      // The parse() / expand() pipeline:
      //   1. Build an input string with DTSTART + RRULE lines
      //   2. Parse it with rrule-ts parse()
      //   3. Expand to c.count occurrences
      //   4. Format as ISO-8601 strings
      //   5. Deep-equal c.expectedOccurrences
      //
      // NOTE: expand() currently throws 'not implemented'. This block is
      // inside describe.skip so it never runs until the expansion phase.
      const dtLine = c.tzid
        ? `DTSTART;TZID=${c.tzid}:${c.dtstart.replace(/[-:]/g, '').replace('T', 'T')}`
        : `DTSTART:${c.dtstart.replace(/[-:]/g, '').replace('T', 'T')}`
      void dtLine // referenced above; keep linter happy

      // TODO(expansion-phase): wire this once expand() is real:
      //
      //   import { parse } from 'rrule-ts'
      //   const parsed = parse(`${dtLine}\nRRULE:${c.rrule}`)
      //   if (!parsed.ok) throw new Error(parsed.error)
      //   const occurrences = expand(parsed.value, c.count)
      //   const isoStrings = occurrences.map(inst => inst.toString())
      //   expect(isoStrings).toEqual(c.expectedOccurrences)

      // Placeholder — keeps TypeScript happy that expand is referenced.
      void expand
      expect(true).toBe(true) // will be replaced by the real assertion above
    })
  }
})

// Explicit it.todo entries for the three headline assertion categories,
// so test runners show "pending" output and reviewers know what comes next.
it.todo('EXPANSION PHASE: all RFC §3.8.5.3 examples match dateutil oracle exactly')
it.todo('EXPANSION PHASE: all DST cases match dateutil oracle exactly (LA/Berlin/LordHowe/Apia)')
it.todo('EXPANSION PHASE: all generated fast-check cases match dateutil oracle exactly')
