// Differential conformance test: rrule-ts vs python-dateutil.
//
// The corpus (corpus/corpus.json) was generated by running the fast-check
// generator + hardcoded RFC §3.8.5.3 + DST seed cases through the Python
// dateutil oracle. It is committed so CI is hermetic: Python is not needed
// to run these tests, only to regenerate the corpus.
//
// ACTIVE TEST: corpus sanity check (always runs, never skipped).
// DIFF TESTS: live assertions comparing expand() output to each case's
//   expectedOccurrences. DST-crossing cases are in KNOWN_GAPS (skip-listed).

import { describe, it, expect } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve, dirname } from 'node:path'
import { fileURLToPath } from 'node:url'
import { parse, expand } from 'rrule-ts'

const __dirname = dirname(fileURLToPath(import.meta.url))
const corpusPath = resolve(__dirname, '..', 'corpus', 'corpus.json')

// ---------------------------------------------------------------------------
// Corpus type
// ---------------------------------------------------------------------------

interface CorpusCase {
  id: string
  label: string
  rrule: string
  dtstart: string
  tzid: string | null
  count: number
  expectedOccurrences: string[]
}

interface Corpus {
  version: string
  oracleVersion: string
  generatedAt: string
  totalCases: number
  cases: CorpusCase[]
}

// ---------------------------------------------------------------------------
// Load corpus once
// ---------------------------------------------------------------------------

const corpus: Corpus = JSON.parse(readFileSync(corpusPath, 'utf-8'))

// ---------------------------------------------------------------------------
// Known gaps: cases that are deferred to a follow-up DST-correctness pass.
//
// All entries in this set must have a documented reason. Every non-listed case
// MUST pass; do NOT add non-DST failures here.
// ---------------------------------------------------------------------------

/**
 * Cases that are intentionally skipped in this release.
 *
 * Reason codes:
 *   GAP  - Spring-forward gap: dateutil represents the nonexistent wall-clock
 *          time using the pre-gap UTC offset (e.g. 02:30-08:00 in a gap where
 *          02:00-03:00 PST does not exist). Temporal prohibits instants inside
 *          a DST gap and always normalises to the nearest valid time (shifting
 *          the wall-clock forward). Both representations resolve to the same
 *          epoch milliseconds, but the ISO strings differ. This is a genuine
 *          dateutil quirk for nonexistent times that Temporal cannot replicate
 *          without producing invalid instants.
 */
const KNOWN_GAPS: Map<string, string> = new Map([
  // Spring-forward GAP cases: dateutil keeps the nonexistent wall-clock time
  // with the pre-gap offset (fold=0 behaviour). Temporal shifts the wall-clock
  // forward to the first valid post-gap instant. Same epoch, different string.
  [
    'dst-la-spring-daily',
    'GAP: 02:30 in LA spring-forward gap; dateutil gives 02:30-08:00 (pre-gap offset, invalid instant); Temporal normalises to 03:30-07:00 (same epoch ms, valid instant)',
  ],
  [
    'dst-berlin-spring-daily',
    'GAP: 02:00 in Berlin spring-forward gap; dateutil gives 02:00+01:00 (pre-gap, invalid); Temporal normalises to 03:00+02:00 (same epoch)',
  ],
  [
    'dst-lord-howe-spring-daily',
    'GAP: 02:00 in Lord Howe 30-min spring-forward gap; dateutil gives 02:00+10:30 (pre-gap, invalid); Temporal normalises to 02:30+11:00 (same epoch)',
  ],
])

// ---------------------------------------------------------------------------
// Formatter: convert a Temporal occurrence to the ISO-8601 string format
// used in the corpus (offset without IANA timezone annotation).
// ---------------------------------------------------------------------------

function formatOccurrence(occ: unknown): string {
  const s = String((occ as { toString(): string }).toString())
  // Temporal.ZonedDateTime.toString() appends "[Timezone/Name]" which the
  // corpus does not include. Strip it so the comparison is against the
  // offset-only format that python-dateutil produces.
  return s.replace(/\[.*\]$/, '')
}

// ---------------------------------------------------------------------------
// ACTIVE: corpus sanity checks — always run, prove the harness is not vacuous
// ---------------------------------------------------------------------------

describe('conformance corpus sanity', () => {
  it('corpus file loads and is non-empty', () => {
    expect(corpus).toBeDefined()
    expect(corpus.cases).toBeInstanceOf(Array)
    expect(corpus.cases.length).toBeGreaterThan(0)
  })

  it('corpus has required metadata fields', () => {
    expect(corpus.version).toBe('1')
    expect(corpus.oracleVersion).toContain('python-dateutil')
    expect(corpus.generatedAt).toMatch(/^\d{4}-\d{2}-\d{2}T/)
    expect(corpus.totalCases).toBe(corpus.cases.length)
  })

  it('every case has required fields (id, label, rrule, dtstart, count, expectedOccurrences)', () => {
    for (const c of corpus.cases) {
      expect(c.id, `case ${c.id}: missing id`).toBeTruthy()
      expect(c.label, `case ${c.id}: missing label`).toBeTruthy()
      expect(c.rrule, `case ${c.id}: missing rrule`).toBeTruthy()
      expect(c.dtstart, `case ${c.id}: missing dtstart`).toBeTruthy()
      expect(c.count, `case ${c.id}: count must be >= 1`).toBeGreaterThanOrEqual(1)
      expect(c.expectedOccurrences, `case ${c.id}: missing expectedOccurrences`).toBeInstanceOf(
        Array
      )
      expect(
        c.expectedOccurrences.length,
        `case ${c.id}: expectedOccurrences is empty`
      ).toBeGreaterThan(0)
    }
  })

  it('every expectedOccurrence is an ISO-8601-like string', () => {
    for (const c of corpus.cases) {
      for (const occ of c.expectedOccurrences) {
        expect(occ, `case ${c.id}: occurrence "${occ}" must be ISO-8601`).toMatch(
          /^\d{4}-\d{2}-\d{2}(T\d{2}:\d{2}:\d{2}(Z|[+-]\d{2}:\d{2})?)?$/
        )
      }
    }
  })

  it('corpus covers all 7 FREQ values', () => {
    const freqSet = new Set(corpus.cases.map((c) => c.rrule.match(/FREQ=(\w+)/)?.[1]))
    for (const freq of ['SECONDLY', 'MINUTELY', 'HOURLY', 'DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY']) {
      expect(freqSet, `corpus must include at least one ${freq} case`).toContain(freq)
    }
  })

  it('corpus includes DST cases for expected zones', () => {
    const tzids = new Set(corpus.cases.map((c) => c.tzid).filter(Boolean))
    expect(tzids).toContain('America/Los_Angeles')
    expect(tzids).toContain('Europe/Berlin')
    expect(tzids).toContain('Australia/Lord_Howe')
    expect(tzids).toContain('Pacific/Apia')
  })

  it('corpus includes RFC §3.8.5.3 seed cases', () => {
    const ids = new Set(corpus.cases.map((c) => c.id))
    // Spot-check a few of the hardcoded RFC cases by id.
    expect(ids).toContain('rfc-daily-count-10')
    expect(ids).toContain('rfc-weekly-count-10')
    expect(ids).toContain('rfc-monthly-bysetpos-neg1-th')
    expect(ids).toContain('rfc-yearly-byweekno-20-mo')
  })
})

// ---------------------------------------------------------------------------
// LIVE: differential diff assertions — expand() vs dateutil oracle.
//
// Every case in the corpus is tested. Cases in KNOWN_GAPS are skipped with
// a documented reason. ALL non-skipped cases must pass.
// ---------------------------------------------------------------------------

describe('conformance diff: rrule-ts expand() vs dateutil oracle', () => {
  for (const c of corpus.cases) {
    const gapReason = KNOWN_GAPS.get(c.id)
    if (gapReason !== undefined) {
      it.skip(`[KNOWN_GAP] ${c.id}: ${c.label} — ${gapReason}`, () => {})
      continue
    }

    it(`${c.id}: ${c.label}`, () => {
      // Build DTSTART line in iCalendar basic format.
      // The corpus stores dtstart as ISO-8601 extended; convert to basic.
      const dtstartBasic = c.dtstart.replace(/[-:]/g, '').replace('T', 'T')
      const dtLine = c.tzid ? `DTSTART;TZID=${c.tzid}:${dtstartBasic}` : `DTSTART:${dtstartBasic}`

      const parsed = parse(`${dtLine}\nRRULE:${c.rrule}`)
      if (!parsed.ok) {
        throw new Error(`parse failed for ${c.id}: ${parsed.error}`)
      }

      const occurrences = expand(parsed.value, c.count)
      const isoStrings = occurrences.map(formatOccurrence)
      expect(isoStrings).toEqual(c.expectedOccurrences)
    })
  }
})
